DROP TABLE IF EXISTS "Character";
CREATE TABLE Character (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Character TEXT, Player TEXT, Notes TEXT, Alias TEXT,
	Metatype TEXT, Ethnicity TEXT, Age INT, Sex TEXT, Height TEXT, Weight TEXT, 
	StreetCred TEXT, Notoriety TEXT, PublicAwareness TEXT, Karma INT, TotalKarma INT, 
	Misc TEXT, EdgePoints INT, 	Initiative TEXT, MatrixInitiative TEXT, 
	AstralInitiative TEXT, LifeStyle TEXT, Nuyen TEXT, BaseStat INT, PhysicalDmg INT, 
	StunDmg INT
	-- Body INT, Agility INT, Reaction INT, Strength INT, Willpower INT, 
	-- Logic INT, Intuition INT, Charisma INT, Edge INT, Essence REAL,
	-- MagicResonance INT, 
);

DROP TABLE IF EXISTS "Character_Quality";
CREATE TABLE Character_Quality (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, QID INTEGER, Details TEXT, Karma INT
);

DROP TABLE IF EXISTS "Character_Skill";
CREATE TABLE Character_Skill (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, SID INTEGER, Rating INT, Specialization TEXT, 
	Notes Text
);

DROP TABLE IF EXISTS "Contact";
CREATE TABLE Contact (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, Name TEXT, Loyalty INT, Connection INT, 
	Favor TEXT, Misc TEXT
);

DROP TABLE IF EXISTS "Quality";
CREATE TABLE Quality (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Type TEXT, Cost INT, Description TEXT
);

DROP TABLE IF EXISTS "Skill";
CREATE TABLE Skill (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Type TEXT, `Default` BOOLEAN, 
	SkillGroup INT, Specializations TEXT, Description TEXT, Stat TEXT
);

DROP TABLE IF EXISTS "Deck";
CREATE TABLE Deck (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, GID INTEGER, Model TEXT, Attack INT, Sleaze INT, 
	DeviceRating INT, DataProcessing INT, Firewall INT, MatrixDmg INT, MaxMatrixDmg INT
);

DROP TABLE IF EXISTS "Deck_Program";
CREATE TABLE Deck_Program (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, DID INTEGER, PID INTEGER, Rating INT
);

DROP TABLE IF EXISTS "Program";
CREATE TABLE Program (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, `Desc` TEXT, Cost INT
);

DROP TABLE IF EXISTS "Vehicle";
CREATE TABLE Vehicle (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, Name TEXT, Acceleration INT, Pilot INT, 
	Armor INT, Hadling TEXT, Speed TEXT, Body INT, Sensor INT, Notes TEXT
);

DROP TABLE IF EXISTS "Gear";
CREATE TABLE Gear (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, Name TEXT, `Desc` TEXT, Rating INT, 
	Count INT, Active BOOLEAN
);

DROP TABLE IF EXISTS "RangedWeapon";
CREATE TABLE RangedWeapon (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, GID INTEGER, Mode INT, Dmg TEXT, Acc TEXT, AP INT, RC INT,
	Ammo INT, ClipSize TEXT
);

DROP TABLE IF EXISTS "Mode";
CREATE TABLE Mode (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, `Desc` TEXT, Ammo INT
);

DROP TABLE IF EXISTS "Weapon_Mode";
CREATE TABLE Weapon_Mode (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, WID INTEGER, MID INTEGER
);

DROP TABLE IF EXISTS "MeleeWeapon";
CREATE TABLE MeleeWeapon (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, GID INTEGER, Dmg TEXT, Acc TEXT, Reach INT, AP INT
);

DROP TABLE IF EXISTS "Armor";
CREATE TABLE Armor (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, GID INTEGER, `Set` TEXT, Notes TEXT
);

DROP TABLE IF EXISTS "Spell";
CREATE TABLE Spells (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Type TEXT, Target TEXT, Range TEXT, 
	Duration TEXT, Drain TEXT
);

DROP TABLE IF EXISTS "Character_Spell";
CREATE TABLE Character_Spell (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, SID INTEGER
);

DROP TABLE IF EXISTS "Power";
CREATE TABLE Powers (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, Rating INT, Notes TEXT
);

DROP TABLE IF EXISTS "Character_Augmentation";
CREATE TABLE Character_Augmentation (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, GID INTEGER, AID INTEGER, Ess REAL
);

DROP TABLE IF EXISTS "Augmentation";
CREATE TABLE Augmentation (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, `Desc` TEXT, MaxRating INT, Capacity INT, 
	Avalibility TEXT, Cost INT, Type TEXT
);

DROP TABLE IF EXISTS "Augmentation_Stat";
CREATE TABLE Augmentation_Stat (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, AID INTEGER, SID INTEGER, Rating INT
);

DROP TABLE IF EXISTS "Stat";
CREATE TABLE Stat (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, Body INT, Agility INT, Reaction INT, Strength INT, 
	Willpower INT, Logic INT, Intuition INT, Charisma INT, Edge INT, Essence REAL, 
	MagicResonance INT
);

DROP TABLE IF EXISTS "Character_Stat";
CREATE TABLE Character_Stat (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, CID INTEGER, SID INTEGER, Active BOOLEAN
);

